apiVersion: v1
kind: Secret
metadata:
  name: {{ include "car-api.fullname" . }}
  labels:
    {{- include "car-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secret.databaseUrl | quote }}
